Repository scenario-labs/Scenario-Unity, pull requests merged in 2024-03, with the labels that each got.

#149 fix: model list display is broken
  package/Editor/Models/Models.cs
  package/Editor/Models/ModelsUI.cs
Labels: bug

#150 fix: remove the sliders from the controlnet modes and leave the values the same as in the webapp
  package/Editor/PromptWindow/PromptWindow.cs
  package/Editor/PromptWindow/PromptWindowUI.cs
  package/Editor/PromptWindow/Views/ControlNetView.cs
Labels: enhancement

#160 chore(devexp): remove release please
  .github/workflows/release-please.yml
  .release-please-manifest.json
  README.md
  package-lock.json
  package.json
  package/CHANGELOG.md
  package/CHANGELOG.md.meta
  package/package.json
  release-please-config.json
Labels: ci
